[app]
title="工具"
package.name="mytool"
package.domain="com.mytool"
source.dir="."
source.include_exts=py，png，jpg
版本=0.1
要求=python3，烧瓶
android.service=True
安卓。apptheeme="@android:style/Theme。无显示"
安卓。权限=Internet，访问网络状态
icon.filename="icon.png"
